### ISSUE TITLE
pg_ready ignores provided arguments.

### ISSUE THREAD

**Issue by mvanderlee** [peter-evans/docker-compose-healthcheck#13]
pg_ready ignores the user and database arguments. A more reliable check is `psql -U postgres -c "\q"`

I've tested this by having an initdb script that sleeps and then create a new database and user. pg_ready always returns `0` even when the database and user don't yet exist.

**Comment by peter-evans** [comment]
Hi @mvanderlee 

Apologies for the slow response.

I've taken another look at `pg_isready` and a past pull request I received [here](https://github.com/peter-evans/docker-compose-healthcheck/pull/12) and decided that the best thing to do here is just remove the arguments specifying the user. I've merged PR https://github.com/peter-evans/docker-compose-healthcheck/pull/14 for that change. We can just remove them because we only care if Postgres is available, not if specific users/databases exist. In the next step we run the database migrations to create those.

**Comment by Simran-B** [comment]
FYI When using Docker Compose `healthcheck` to determine readiness, it is crucial to use the hostname (defined by the `services` key), like `pg_isready --host=THE_HOSTNAME`, to not incorrectly return successfully because Postgres accepts local connections during initialization.
